repos:
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    - id: mypy
      args: [--ignore-missing-imports]
  - repo: local
    hooks:
    - id: detect_cassette_secrets
      name: Check for secrets in VCR cassettes
      language: script
      files: "tests/cassettes/.*"
      types: [yaml]
      entry: scripts/detect_cassette_secrets.zsh